apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hello-world-app
  labels:
    app.kubernetes.io/name: hello-world-app
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: hello-world-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
